name: language_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.5
  speech_to_text: ^7.3.0
  shared_preferences: ^2.2.2
  flutter_tts: ^3.8.3
  provider: ^6.1.5+1
  http: ^1.6.0
  fl_chart: ^1.1.1
  lottie: ^3.3.2
  flutter_markdown: ^0.7.7+1
  model_viewer_plus: ^1.7.2 
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - test/test_assets/russian_sample.wav  
    - test/data/viseme.txt
    - assets/images/background.png
    - assets/images/logo.png
    - assets/images/google_icon.png
    - assets/images/girl_image.png
    - assets/logo.png
    - assets/avatar/avatar1.png
    - assets/animations/Success.json
    - ios/Runner/Assets.scnassets/ClaraAvatar.usdz
    - ios/Runner/Assets.scnassets/KarlAvatar.usdz
    - assets/models/clara.glb  
    - assets/models/karl.glb
    - assets/profile_user.png